POST https://node-basic-final.onrender.com/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://node-basic-final.onrender.com/videos

###
PUT https://node-basic-final.onrender.com/videos/63b89c8e-166e-4346-bb72-53b58215316d
Content-type: application/json

{
    "title": "Video 03",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE  http://localhost:3333/videos/63b89c8e-166e-4346-bb72-53b58215316d